import * as Joi from 'joi';

export const validationSchema = Joi.object({
	APP_ID: Joi.string().required(),
	NODE_ENV: Joi.string().required(),
	PORT: Joi.number().required(),
	// URL: Joi.string().required(),
	DATABASE_URL: Joi.string().required(),
	JWT_ACCESS_TIME: Joi.number().required(),
	JWT_ACCESS_PUBLIC_KEY: Joi.string().required(),
	JWT_ACCESS_PRIVATE_KEY: Joi.string().required(),
	JWT_CONFIRMATION_PUBLIC_KEY: Joi.string().required(),
	JWT_CONFIRMATION_PRIVATE_KEY: Joi.string().required(),
	JWT_CONFIRMATION_TIME: Joi.number().required(),
	JWT_RESET_PASSWORD_PUBLIC_KEY: Joi.string().required(),
	JWT_RESET_PASSWORD_PRIVATE_KEY: Joi.string().required(),
	JWT_RESET_PASSWORD_TIME: Joi.number().required(),
	JWT_REFRESH_PUBLIC_KEY: Joi.string().required(),
	JWT_REFRESH_PRIVATE_KEY: Joi.string().required(),
	JWT_REFRESH_TIME: Joi.number().required(),
	EMAIL_HOST: Joi.string().required(),
	EMAIL_PORT: Joi.number().required(),
	EMAIL_SECURE: Joi.bool().required(),
	EMAIL_USER: Joi.string().email().required(),
	EMAIL_PASSWORD: Joi.string().required(),
	OAUTH_GOOGLE_ID: Joi.string().required(),
	OAUTH_GOOGLE_SECRET: Joi.string().required(),
	OAUTH_GOOGLE_REDIRECT_URL: Joi.string().required(),
	OAUTH_FACEBOOK_ID: Joi.number().required(),
	OAUTH_FACEBOOK_SECRET: Joi.string().required(),
	OAUTH_FACEBOOK_REDIRECT_URL: Joi.string().required(),
	PASSWORD_RESET_LIMIT: Joi.number().required(),
	EMAIL_MODEL_TOKENS_LIMIT: Joi.number().required(),
	LIFETIME_OF_ONE_PASSWORD_RESET_ATTEMPT: Joi.number().required(),
	CRYPTO_RANDOM_BYTES: Joi.number().required(),
	EMAIL_TOKEN_EXPIRATION_TIME: Joi.number().required(),
	MESSAGE_UPDATE_TIME: Joi.number().required(),
	MESSAGE_PUBLIC_KEY: Joi.string().required(),
	MESSAGE_PRIVATE_KEY: Joi.string().required(),
	MAX_ATTEMPT_MESSAGE_RESET_EMAIL: Joi.number().required(),
	CONFIRMATION_CODE_RESEND_EMAIL_INTERVAL: Joi.number().required(),
	DAILY_RESET_EMAIL_CODE_ATTEMPTS_LIMIT: Joi.number().required(),
	EMAIL_RESET_INTERVAL: Joi.number().required(),
	PASSWORD_RESET_INTERVAL: Joi.number().required(),
	CONFIRMATION_CODE_RESEND_PASSWORD_INTERVAL: Joi.number().required(),
	DAILY_RESET_PASSWORD_CODE_ATTEMPTS_LIMIT: Joi.number().required(),
	MAX_ATTEMPT_MESSAGE_RESET_PASSWORD: Joi.number().required(),
	TIME_LIVE_RESET_EMAIL_CODE: Joi.number().required(),
	TIME_LIVE_RESET_PASSWORD_CODE: Joi.number().required(),
	ELASTICSEARCH_ADS_INDEX: Joi.string().required(),
	ELASTICSEARCH_LOGGER_ERROR_INDEX: Joi.string().required(),
	ELASTICSEARCH_LOGGER_OTHER_INDEX: Joi.string().required(),
	GOOGLE_RECAPTCHA_SECRET: Joi.string().required(),
	I18N_LANGUAGE: Joi.string().required(),
	I18N_WATCH: Joi.string().required()
	// HASH_OUTPUT_FORMAT: Joi.BufferEncoding().required()
	// COOKIE_SECRET_KEY: Joi.string().required
});
